import type { Metadata } from "next";
export const metadata: Metadata = { title: "Anthony Johnson — Founder, CCOS", description: "The Founder behind Community Connection Operating Systems and its portfolio of focused ventures.", alternates: { canonical: "/founder" } };
const Header=()=> <header className="site-header"><div className="header-inner"><a className="brand" href="/" aria-label="CCOS home"><img src="/identity/CCOS_Wordmark_Primary_Light_v1.0.svg" alt="CCOS" width="174" height="45" /></a><nav aria-label="Primary navigation"><a href="/#company">Company</a><a href="/#model">Operating model</a><a href="/#portfolio">Portfolio</a><a href="/founder" aria-current="page">Founder</a><a className="nav-cta" href="mailto:anthony@ccos.systems">Build what matters</a></nav></div></header>;
export default function FounderPage(){return <main><a className="skip-link" href="#founder-content">Skip to content</a><Header/><div id="founder-content">
  <section className="founder-hero" aria-labelledby="founder-title"><figure><img src="/founder/anthony-johnson.png" alt="Anthony Johnson, Founder of CCOS" width="1254" height="1254" /></figure><div className="founder-copy"><p className="eyebrow">Founder / CCOS</p><p className="founder-name">Anthony Johnson</p><h1 id="founder-title">Building institutions people can understand and trust.</h1><p>CCOS is the operating company behind a portfolio of focused products and ventures. Anthony sets its direction, holds final responsibility for consequential decisions, and keeps the relationship between ambition and accountability visible.</p><a className="button" href="#commitment">My commitment <span>→</span></a></div><aside><span>Origin</span><span>Accountability</span><span>Conviction</span><span>Human trust</span></aside></section>
  <section className="principles" id="commitment" aria-labelledby="principles-title"><div className="principles-head"><h2 id="principles-title">Guided by a clear set of principles.</h2><p>These principles shape how we build, operate, and grow.</p></div><div className="principles-grid"><article><span>01</span><h3>Purpose before scale.</h3><p>We prioritize real value, meaningful use, and long-term impact over empty growth.</p></article><article><span>02</span><h3>Evidence before claims.</h3><p>We communicate clearly, avoid exaggeration, and let the work speak for itself.</p></article><article><span>03</span><h3>Accountability in view.</h3><p>We hold ourselves to a higher standard because people, communities, and trust are on the line.</p></article><blockquote>“A more connected tomorrow is a choice.”<cite>Anthony Johnson</cite></blockquote></div></section>
  <section className="founder-building"><div><p className="eyebrow">Currently building</p><h2>One operating company.<br/>Three distinct expressions.</h2><p>Each venture keeps the identity and focus its audience requires. CCOS supplies the shared institutional home, governance, and continuity behind the work.</p></div><div className="building-list"><article><span>01 / Opportunity intelligence</span><h3>Ninthline</h3></article><article><span>02 / Community infrastructure</span><h3>Forney Connected</h3></article><article><span>03 / Employment infrastructure</span><h3>ForneyJobs</h3></article></div></section>
  <section className="founder-context"><img src="/photography/workshop.webp" alt="A working environment grounded in craft, tools, and practical responsibility" width="1600" height="1067"/><div><p className="eyebrow light">Provenance</p><h2>The work has a name behind it.</h2><p>Anthony Johnson is the Founder of Community Connection Operating Systems LLC. He retains responsibility for company direction, reserved decisions, and the standards that connect CCOS to the ventures it operates.</p><a className="text-link on-dark" href="mailto:anthony@ccos.systems">anthony@ccos.systems <span>→</span></a></div></section>
  </div><footer><img src="/identity/CCOS_Wordmark_White_v1.0.svg" alt="CCOS" width="150" height="39"/><div><p>Community Connection Operating Systems LLC</p><p>Products, brands, systems, and community infrastructure.</p><a href="mailto:anthony@ccos.systems">anthony@ccos.systems</a></div><p>© {new Date().getUTCFullYear()} CCOS</p></footer></main>}
