const ventures = [
  { name: "Ninthline", category: "Opportunity intelligence", image: "/photography/road.webp", description: "Finds meaningful signals, investigates context, and develops specific opportunities worth evaluating." },
  { name: "Forney Connected", category: "Local information / real community", image: "/photography/architecture.webp", description: "Helps a growing community understand the information, people, and activity shaping local life." },
  { name: "ForneyJobs", category: "Local jobs / real opportunity", image: "/photography/workshop.webp", description: "Makes verified local work easier to discover, evaluate, and pursue." },
];
const Header = () => <header className="site-header"><div className="header-inner"><a className="brand" href="#top" aria-label="CCOS home"><img src="/identity/CCOS_Wordmark_Primary_Light_v1.0.svg" alt="CCOS" width="174" height="45" /></a><nav aria-label="Primary navigation"><a href="#company">Company</a><a href="#model">Operating model</a><a href="#portfolio">Portfolio</a><a href="/founder">Founder</a><a className="nav-cta" href="mailto:anthony@ccos.systems">Build what matters</a></nav></div></header>;
const Footer = () => <footer><img src="/identity/CCOS_Wordmark_White_v1.0.svg" alt="CCOS" width="150" height="39" /><div><p>Community Connection Operating Systems LLC</p><p>Products, brands, systems, and community infrastructure.</p><a href="mailto:anthony@ccos.systems">anthony@ccos.systems</a></div><p>© {new Date().getUTCFullYear()} CCOS</p></footer>;
export default function Home() { return <main><a className="skip-link" href="#content">Skip to content</a><Header /><div id="content">
  <section className="home-hero" id="top" aria-labelledby="hero-title"><div className="hero-copy"><p className="eyebrow">Community Connection Operating Systems</p><h1 id="hero-title">Building the operating layer behind useful connection.</h1><p>CCOS develops and operates products, brands, and systems that help people, organizations, information, resources, and opportunity relate more usefully.</p><div className="actions"><a className="button" href="#company">Our approach <span>→</span></a><a className="text-link" href="#portfolio">Explore the portfolio</a></div></div><figure className="hero-photo"><img src="/photography/architecture.webp" alt="Concrete architecture shaped by natural light and strong structural geometry" width="2000" height="1333" /><figcaption><span>People</span><span>Ideas</span><span>Resources</span><span>Opportunity</span><strong>A stronger tomorrow</strong><small>A more connected tomorrow takes intentional infrastructure.</small></figcaption></figure></section>
  <section className="registry" aria-label="Company registry"><dl><div><dt>Entity</dt><dd>Community Connection<br/>Operating Systems LLC</dd></div><div><dt>Role</dt><dd>Operating company</dd></div><div><dt>Orientation</dt><dd>Products, brands, systems,<br/>and community infrastructure</dd></div></dl></section>
  <section className="company-portfolio" id="company" aria-labelledby="company-title"><div className="company-copy"><p className="eyebrow">Distinct work needs a coherent institutional home</p><h2 id="company-title">Different products.<br/>A shared purpose.</h2><p>CCOS provides ownership, operating discipline, and continuity that allow each product to remain specific to its audience and purpose while benefiting from a shared foundation.</p><a className="text-link green" href="#model">Learn about CCOS <span>→</span></a></div><div className="venture-tiles" id="portfolio">{ventures.map((v)=><article key={v.name}><img src={v.image} alt="" width="1200" height="900" /><div><h3>{v.name}</h3><p>{v.category}</p><span className="sr-only">{v.description}</span></div></article>)}</div></section>
  <section className="model" id="model" aria-labelledby="model-title"><div className="model-image" aria-hidden="true"></div><div className="model-copy"><p className="eyebrow light">Build / Govern / Steward</p><h2 id="model-title">The operating model for what comes next.</h2><p>We build, govern, and steward enduring products and brands that create real value in the communities they serve.</p><a className="text-link on-dark" href="/founder">Our operating model <span>→</span></a></div><ol><li><span>01</span><div><h3>Build</h3><p>Establish and launch useful products and brands.</p></div></li><li><span>02</span><div><h3>Govern</h3><p>Maintain standards, accountability, and clarity.</p></div></li><li><span>03</span><div><h3>Steward</h3><p>Ensure continuity, trust, and long-term value.</p></div></li></ol></section>
  <section className="place"><p className="eyebrow">A more connected tomorrow</p><h2>Built for people.<br/>Grounded in place.</h2><p>CCOS exists to strengthen the connections that help communities, organizations, and individuals move forward.</p><a className="text-link green" href="mailto:anthony@ccos.systems">Build what matters <span>→</span></a></section>
  <section className="founder-feature" aria-labelledby="founder-heading"><figure><img src="/founder/anthony-johnson.png" alt="Anthony Johnson, Founder of CCOS" width="1254" height="1254" /></figure><div><p className="eyebrow light">Founder / CCOS</p><h2 id="founder-heading">Building institutions people can understand and trust.</h2><p>Anthony Johnson founded CCOS to build useful systems with clear ownership, durable evidence, and accountable decisions.</p><a className="button" href="/founder">Meet the Founder <span>→</span></a></div></section>
  <section className="contact"><p className="eyebrow">A durable operating home</p><h2>Build with purpose.<br/>Operate with accountability.</h2><a className="button" href="mailto:anthony@ccos.systems">anthony@ccos.systems <span>→</span></a></section>
  </div><Footer /></main> }
